/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { findFlight$Json } from '../fn/flight/find-flight-json';
import { FindFlight$Json$Params } from '../fn/flight/find-flight-json';
import { findFlight$Plain } from '../fn/flight/find-flight-plain';
import { FindFlight$Plain$Params } from '../fn/flight/find-flight-plain';
import { FlightRm } from '../models/flight-rm';
import { searchFlight$Json } from '../fn/flight/search-flight-json';
import { SearchFlight$Json$Params } from '../fn/flight/search-flight-json';
import { searchFlight$Plain } from '../fn/flight/search-flight-plain';
import { SearchFlight$Plain$Params } from '../fn/flight/search-flight-plain';

@Injectable({ providedIn: 'root' })
export class FlightService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `searchFlight()` */
  static readonly SearchFlightPath = '/Flight';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchFlight$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Plain$Response(params?: SearchFlight$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlightRm>>> {
    return searchFlight$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchFlight$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Plain(params?: SearchFlight$Plain$Params, context?: HttpContext): Observable<Array<FlightRm>> {
    return this.searchFlight$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `searchFlight$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Json$Response(params?: SearchFlight$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FlightRm>>> {
    return searchFlight$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `searchFlight$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  searchFlight$Json(params?: SearchFlight$Json$Params, context?: HttpContext): Observable<Array<FlightRm>> {
    return this.searchFlight$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FlightRm>>): Array<FlightRm> => r.body)
    );
  }

  /** Path part for operation `findFlight()` */
  static readonly FindFlightPath = '/Flight/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findFlight$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFlight$Plain$Response(params: FindFlight$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<FlightRm>> {
    return findFlight$Plain(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findFlight$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFlight$Plain(params: FindFlight$Plain$Params, context?: HttpContext): Observable<FlightRm> {
    return this.findFlight$Plain$Response(params, context).pipe(
      map((r: StrictHttpResponse<FlightRm>): FlightRm => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `findFlight$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFlight$Json$Response(params: FindFlight$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FlightRm>> {
    return findFlight$Json(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `findFlight$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  findFlight$Json(params: FindFlight$Json$Params, context?: HttpContext): Observable<FlightRm> {
    return this.findFlight$Json$Response(params, context).pipe(
      map((r: StrictHttpResponse<FlightRm>): FlightRm => r.body)
    );
  }

}
